# Day 3 -- Assignment

### Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

In [2]:
arr = np.arange(2, 51, 3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


### Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
# list creation
first_list = []
second_list = []

# taking user input for first list
print("Input for first list:")
for i in range(5):
    first_list.append(int(input()))

print() # printing blank line

# taking user input for second list
print("Input for second list:")

for j in range(5):
    second_list.append(int(input()))

# converting list into numpy array
first_arr = np.array(first_list)
second_arr = np.array(second_list)

print() # printing blank line

# concatenating two numpy array
concatenated_arr = np.concatenate((first_arr, second_arr), axis = 0)
print(concatenated_arr)

print() # printing blank line

# sorting numpy array
sorted_arr = np.sort(concatenated_arr)

print(sorted_arr)

Input for first list:
56
23
42
89
65

Input for second list:
12
55
38
44
79

[56 23 42 89 65 12 55 38 44 79]

[12 23 38 42 44 55 56 65 79 89]


### Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
arr_1D = np.array( [52,71,38,55,79,23,758,80,99] )
print(arr_1D)
print("Shape:",arr_1D.shape)
print("Dimension:",np.ndim(arr_1D))
print("Size:",arr_1D.size)


print()

arr_2D = np.array( [ [81,53,47] , [42,55,16] , [74,28,39] , [62,44,21]] )
print(arr_2D)
print("Shape:",arr_2D.shape)
print("Dimension:",np.ndim(arr_2D))
print("Size:",arr_2D.size)


[ 52  71  38  55  79  23 758  80  99]
Shape: (9,)
Dimension: 1
Size: 9

[[81 53 47]
 [42 55 16]
 [74 28 39]
 [62 44 21]]
Shape: (4, 3)
Dimension: 2
Size: 12


### Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [5]:
arry_1D = np.array( [52,71,38,55,79,23,758,80,99] )

# using np.newaxis
arry_2D = arry_1D[:, np.newaxis]

# using np.expand_dims() method
arry_2D_expanded  = np.expand_dims(arry_1D, 0)

print("Shape:",arry_1D.shape)
print("Dimension:",np.ndim(arry_1D))

print()

print(arry_2D)
print("Shape:",arry_2D.shape)
print("Dimension:",np.ndim(arry_2D))

print()

print(arry_2D_expanded)
print("Shape:",arry_2D_expanded.shape)
print("Dimension:",np.ndim(arry_2D_expanded))

Shape: (9,)
Dimension: 1

[[ 52]
 [ 71]
 [ 38]
 [ 55]
 [ 79]
 [ 23]
 [758]
 [ 80]
 [ 99]]
Shape: (9, 1)
Dimension: 2

[[ 52  71  38  55  79  23 758  80  99]]
Shape: (1, 9)
Dimension: 2


### Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [6]:
zero_arr = np.zeros((4,4))
one_arr = np.ones((4,4))

# np.identity( 3 )

print("Vertical stack of two numpy arrays \n",np.vstack((zero_arr, one_arr)))

print()

print("Horizontal stack of two numpy arrays \n",np.hstack((zero_arr, one_arr)))

Vertical stack of two numpy arrays 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Horizontal stack of two numpy arrays 
 [[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


### Questions 6:
How to get unique items and counts of unique items?

In [7]:
# dictionary can be used to store "unique item" as {key} and "count" of unique item as {value}

item_list = []  # item list created 

total_item = int(input("Total number of item in list = "))

# User enters item name
for item in range(total_item):
    item_list.append(input().strip())

print()
print(item_list)
print()

# Creating dictionary to store unique item and its count
item_dict = {unique_item : item_list.count(unique_item) for unique_item in item_list}

print("Unique Items with item count")

for uItem, count_uItem in item_dict.items():
    print(f"{uItem} : {count_uItem}")

Total number of item in list = 6
Data Science
IOT
AWS
IOT
AWS
ReactJs

['Data Science', 'IOT', 'AWS', 'IOT', 'AWS', 'ReactJs']

Unique Items with item count
Data Science : 1
IOT : 2
AWS : 2
ReactJs : 1
